server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres"
          host: DEFAULT_DB_HOST # will be injected from env
          port: 5432
          database: temporal
          user: DEFAULT_DB_USER # will be injected from env
          password: DEFAULT_DB_PASSWORD # will be injected from env
          maxConns: 20
          maxConnLifetime: "1h"
          tls:
            enabled: true

      visibility:
        driver: "sql"

        sql:
          driver: "postgres"
          host: VISIBILITY_DB_HOST # will be injected from env
          port: 5432
          database: temporal_visibility
          user: VISIBILITY_DB_USER # will be injected from env
          password: VISIBILITY_DB_PASSWORD # will be injected from env
          maxConns: 20
          maxConnLifetime: "1h"
          tls:
            enabled: true

  frontend:
    service:
      type: LoadBalancer
      port: 7233
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
        # or "internal" for internal NLB
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-name: _NLB_NAME_ # will be injected from env
        service.beta.kubernetes.io/aws-load-balancer-subnets: _SUBNETS_ # will be injected from env
        # Requires external DNS
        external-dns.alpha.kubernetes.io/hostname: _FRONTEND_DNS_DOMAIN_ # will be injected from env
        
  replicaCount: 2

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false

web:
  service:
    port: 80
    type: NodePort
  ingress:
    enabled: true
    hosts:
      - "/"
      - _WEB_DNS_DOMAIN_ # will be injected from env
    annotations:
      kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/subnets: _SUBNETS_ # will be injected from env subnet-04ab65750c4461660, subnet-06572f16ee4eddb44

    ingressClassName: alb
