server:
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      datastores:
        default:
          sql:
            createDatabase: false
            manageSchema: false
            pluginName: postgres12
            connectAddr: DEFAULT_DB_HOST:5432 # will be injected from env
            connectProtocol: tcp
            databaseName: temporal
            user: DEFAULT_DB_USER # will be injected from env
            password: DEFAULT_DB_PASSWORD # will be injected from env
            maxConns: 20
            maxConnLifetime: "1h"
            tls:
              enabled: true
        visibility:
          elasticsearch:
            manageSchema: false
            version: v7
            url:
              scheme: https
              host: TEMPORAL_ES_HOSTS # will be injected from env
            username: TEMPORAL_ES_MASTER_USERNAME # will be injected from env
            password: TEMPORAL_ES_MASTER_PASSWORD # will be injected from env
            logLevel: error
            indices:
              visibility: temporal_visibility_v1

  frontend:
    service:
      type: LoadBalancer
      port: 7233
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
        # or "internal" for internal NLB
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-name: _NLB_NAME_ # will be injected from env
        service.beta.kubernetes.io/aws-load-balancer-subnets: _SUBNETS_ # will be injected from env
        # Requires external DNS
        external-dns.alpha.kubernetes.io/hostname: _FRONTEND_DNS_DOMAIN_ # will be injected from env

  replicaCount: 2

web:
  service:
    port: 80
    type: NodePort
  ingress:
    enabled: true
    hosts:
      - "/"
      - _WEB_DNS_DOMAIN_ # will be injected from env
    annotations:
      kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/subnets: _SUBNETS_ # will be injected from env subnet-04ab65750c4461660, subnet-06572f16ee4eddb44

    ingressClassName: alb
  additionalEnv:
    - name: TEMPORAL_CSRF_COOKIE_INSECURE
      value: 'true'
    - name: TEMPORAL_BANNER_TEXT
      value: _TEMPORAL_BANNER_TEXT_ # will be injected from env

embeddedPrometheus:
  server:
    resources:
      limits:
        cpu: "1500m"
        memory: "4096Mi"
      requests:
        cpu: "1000m"
        memory: "1024Mi"
    ingress:
      hosts:
        - "/"
        - _PROMETHEUS_DNS_DOMAIN_ # will be injected from env
      annotations:
        kubernetes.io/ingress.class: "alb"
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
        alb.ingress.kubernetes.io/subnets: _SUBNETS_ # will be injected from env subnet-04ab65750c4461660, subnet-06572f16ee4eddb44

extraObjects:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "temporal.fullname" . }}-prometheus-config
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
    data:
      prometheus.yml: |
        global:
          scrape_interval: 30s
          evaluation_interval: 30s
        scrape_configs:
          - job_name: temporal
            metrics_path: /metrics
            static_configs:
              - targets:
                  - {{ include "temporal.componentname" (list . "frontend-headless") }}:9090
                  {{- if (index .Values.server "internal-frontend").enabled }}
                  - {{ include "temporal.componentname" (list . "internal-frontend-headless") }}:9090
                  {{- end }}
                  {{- if .Values.server.history.enabled }}
                  - {{ include "temporal.componentname" (list . "history-headless") }}:9090
                  {{- end }}
                  {{- if .Values.server.matching.enabled }}
                  - {{ include "temporal.componentname" (list . "matching-headless") }}:9090
                  {{- end }}
                  {{- if .Values.server.worker.enabled }}
                  - {{ include "temporal.componentname" (list . "worker-headless") }}:9090
                  {{- end }}
          - job_name: prometheus
            metrics_path: /metrics
            static_configs:
              - targets:
                  - 127.0.0.1:9090
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "temporal.fullname" . }}-prometheus
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: {{ include "temporal.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: prometheus
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "temporal.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/component: prometheus
        spec:
          containers:
            - name: prometheus
              image: prom/prometheus:v2.53.3
              imagePullPolicy: IfNotPresent
              args:
                - --config.file=/etc/prometheus/prometheus.yml
                - --storage.tsdb.path=/prometheus
                - --web.console.libraries=/etc/prometheus/console_libraries
                - --web.console.templates=/etc/prometheus/consoles
              ports:
                - name: http
                  containerPort: 9090
              resources:
                limits:
                  cpu: {{ default "1500m" .Values.embeddedPrometheus.server.resources.limits.cpu | quote }}
                  memory: {{ default "4096Mi" .Values.embeddedPrometheus.server.resources.limits.memory | quote }}
                requests:
                  cpu: {{ default "1000m" .Values.embeddedPrometheus.server.resources.requests.cpu | quote }}
                  memory: {{ default "1024Mi" .Values.embeddedPrometheus.server.resources.requests.memory | quote }}
              volumeMounts:
                - name: config
                  mountPath: /etc/prometheus
                - name: storage
                  mountPath: /prometheus
          volumes:
            - name: config
              configMap:
                name: {{ include "temporal.fullname" . }}-prometheus-config
            - name: storage
              emptyDir: {}
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "temporal.fullname" . }}-prometheus
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
      ports:
        - name: http
          port: 80
          targetPort: 9090
          protocol: TCP
  - |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: {{ include "temporal.fullname" . }}-prometheus
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
      annotations:
        {{- toYaml .Values.embeddedPrometheus.server.ingress.annotations | nindent 8 }}
    spec:
      ingressClassName: alb
      rules:
        - host: {{ index .Values.embeddedPrometheus.server.ingress.hosts 1 | trim | quote }}
          http:
            paths:
              - path: {{ index .Values.embeddedPrometheus.server.ingress.hosts 0 | trim | quote }}
                pathType: Prefix
                backend:
                  service:
                    name: {{ include "temporal.fullname" . }}-prometheus
                    port:
                      number: 80
